### ISSUE TITLE
another classical bug in sequences

### ISSUE THREAD

**Issue by haykp** [Practical-UVM-Step-By-Step/Practical-UVM-Step-By-Step#7]
https://verificationacademy.com/forums/uvm/uvm-phasing-mechanism-inside-sequence

never raise/drop objections in sequence

**Comment by Practical-UVM-Step-By-Step** [comment]
Thanks!
I'm going to redo a lot of the examples in this github repo. I'm prepping a release that will be out in a couple of weeks or so because the IEEE version is being prepped and that has both the 1.2 and IEEE versions side by side so people can compare.  I need to copy that branch over to this one.


Changes are:
1) removal of some of  the phases from all components
2) use of automatic_phase_objection in all sequences except for a couple of examples
3) general methodology cleanup.

Typical log file based cleanup.. Some of the heartbeat tests were reworked.

Would you be in a position to test drive it if I gave you a branch and share your comments?
Thanks!
Srivatsa

**Comment by Practical-UVM-Step-By-Step** [comment]
This has been fixed using set_automatic_phase_objection. Can you look?
